stages:
  - build
  - deploy
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  KUBECONFIG: $CI_PROJECT_DIR/.kube/config

# Build Stage
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd app
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG

# Deploy Stage
deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - apt-get update && apt-get install -y curl apt-transport-https
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - chmod +x minikube
    - install minikube /usr/local/bin/
    - minikube start --driver=docker
    - minikube status
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - helm repo add stable https://charts.helm.sh/stable
    - helm repo update
    - helm upgrade --install rick-and-morty ./rick-and-morty-api --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_SHA

# Test Stage
test:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -f http://$(minikube ip)/healthcheck || exit 1
    - curl -f http://$(minikube ip)/characters || exit 1
