stages:
  - build
  - deploy
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  KUBECONFIG: $CI_PROJECT_DIR/.kube/config

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd app
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  services:
    - docker:dind
  script:
    - apt-get update && apt-get install -y curl apt-transport-https
    - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - ls -lh minikube  # Verify the file exists
    - chmod +x minikube
    - install minikube /usr/local/bin/minikube
    - minikube start --driver=docker
    - minikube status
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - helm repo add stable https://charts.helm.sh/stable
    - helm repo update
    - helm upgrade --install rick-and-morty ./rick-and-morty-api --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_SHA

test:
  stage: test
  image: curlimages/curl:latest
  script:
  |
    - APP_IP=$(minikube ip)
    - echo "App IP: $APP_IP"
    - curl -f http://$APP_IP/healthcheck || exit 1
    - curl -f http://$APP_IP/characters || exit 1
