stages:
  - build
  - deploy
  - test


variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  KUBECONFIG: $CI_PROJECT_DIR/.kube/config

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - minikube start --driver=docker
    - kubectl config view --raw > $KUBECONFIG
  script:
    - helm upgrade --install rick-and-morty ./rick-and-morty-api --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_SHA

test:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -f http://app-ingress.local/healthcheck || exit 1
    - curl -f http://app-ingress.local/characters || exit 1
