stages:
  - build
  - deploy
  - test

variables:
  DOCKER_IMAGE: rick-and-morty-api
  IMAGE_TAG: $CI_COMMIT_SHA # Unique tag for each commit

before_script:
  - eval $(minikube docker-env)

build_image:
  stage: build
  script:
    # Build the Docker image inside Minikube's Docker environment
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG ./app

deploy_to_cluster:
  stage: deploy
  script:
    - 'sed -i "s|image: .*|image: $DOCKER_IMAGE:$IMAGE_TAG|g" k8s/deployment.yaml'
    - kubectl apply -f k8s/deployment.yaml

test_application:
  stage: test
  script:
    # Wait for the application to be ready
    - kubectl rollout status deployment/rick-and-morty-api
    - EXTERNAL_IP=$(kubectl get svc rick-and-morty-api -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
    - curl -f http://$EXTERNAL_IP/healthcheack || exit 1
