stages:
  - build
  - deploy
  - test

variables:
  KUBECONFIG: $HOME/.kube/config

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_HUB_USERNAME/rick-and-morty:$CI_COMMIT_SHA app/.
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_HUB_USERNAME/rick-and-morty:$CI_COMMIT_SHA

deploy_to_cluster:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - export KUBECONFIG=$KUBECONFIG  # Ensure the Kubernetes config is used
  tags:
    - rick-and-morty
  script:
    - kubectl config use-context your-cluster-context  # Use the context of your Kubernetes cluster
    - kubectl get nodes  # Verify connection to the cluster
    - 'sed -i "s|image: .*|image: ${DOCKER_HUB_USERNAME}/rick-and-morty:$CI_COMMIT_SHA|g" yamls/deployment.yaml'
    - kubectl apply -f yamls/
    - kubectl rollout status deployment/rick-and-morty-api
  dependencies:
    - build

test_application:
  stage: test
  image: curlimages/curl:latest
  tags:
    - rick-and-morty
  script:
    - |
      EXTERNAL_IP=""
      for i in {1..10}; do
        EXTERNAL_IP=$(kubectl get svc rick-and-morty-api -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        [ -n "$EXTERNAL_IP" ] && break || sleep 5
      done
      echo "Service External IP: $EXTERNAL_IP"
      curl -f http://$EXTERNAL_IP/healthcheck || exit 1
  dependencies:
    - deploy_to_cluster
