rbac:
  create: true
  serviceAccountName: gitlab-runner

runners:
  config: |
    concurrent = 1
    check_interval = 3
    [[runners]]
      name = "k8s-runner"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        service_account = "gitlab-runner"
        privileged = true
        cpu_request = "100m"
        memory_request = "128Mi"
        cpu_limit = "500m"
        memory_limit = "256Mi"
        poll_timeout = 600
        helper_image = "gitlab/gitlab-runner-helper:x86_64-latest"
